# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./

# Install dependencies, ignoring scripts so as not to run prepare automatically
RUN npm install --ignore-scripts

# Build the project
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Expose port if needed (the inspector uses port 3001 as configuration, but the MCP likely uses a different port).
# EXPOSE 3001

# Command to start the server
CMD [ "node", "build/index.js" ]
